---
#
# Playbook to install the ELK stack + Beats
#
- hosts: Remote
  become: yes
  roles:
  - { role: java }
  - { role: elasticsearch }

- hosts: Local
  become: yes
  roles:
  - { role: java }
  - { role: kibana }
  - { role: metricbeat }

